// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf_xuA_Mbp_hywWRP1WKq0I04hYPTfZgE',
    appId: '1:596038897863:web:8810c12b6dda2e0a642ee2',
    messagingSenderId: '596038897863',
    projectId: 'ecommerce-675ee',
    authDomain: 'ecommerce-675ee.firebaseapp.com',
    storageBucket: 'ecommerce-675ee.appspot.com',
    measurementId: 'G-TWGS6N3XTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUih6yf-9QdPKONKWcx8TjNqc2NYpPe0M',
    appId: '1:596038897863:android:dcee9066c2a5726b642ee2',
    messagingSenderId: '596038897863',
    projectId: 'ecommerce-675ee',
    storageBucket: 'ecommerce-675ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWfZjIFiOMY-9pRLC8m2gHqxeSxyJmdr0',
    appId: '1:596038897863:ios:c3c611bc4d12eec5642ee2',
    messagingSenderId: '596038897863',
    projectId: 'ecommerce-675ee',
    storageBucket: 'ecommerce-675ee.appspot.com',
    androidClientId: '596038897863-hcuv7msbceebo5ua3hgl4006kheornai.apps.googleusercontent.com',
    iosClientId: '596038897863-o1255n39uacht1n6p27i5keou35t9ik3.apps.googleusercontent.com',
    iosBundleId: 'com.example.operations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWfZjIFiOMY-9pRLC8m2gHqxeSxyJmdr0',
    appId: '1:596038897863:ios:2aea2c63ef44cdee642ee2',
    messagingSenderId: '596038897863',
    projectId: 'ecommerce-675ee',
    storageBucket: 'ecommerce-675ee.appspot.com',
    androidClientId: '596038897863-hcuv7msbceebo5ua3hgl4006kheornai.apps.googleusercontent.com',
    iosClientId: '596038897863-ktjg53rij7ftlnjshuqkh6pjbs3iut43.apps.googleusercontent.com',
    iosBundleId: 'com.example.operations.RunnerTests',
  );
}
